<div class="container-fluid">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 style="font-family: Calibri Light, sans-serif; font-weight: bold">Pessoas</h4>
            </div>
            <div class="panel-body">
                <div id="DivTudo">
                    <div id="DivA">Nome:</div>
                    <div id="DivB"><?php echo $this->pessoa->nome ?></div>

                </div>
                <hr>
                <div id="DivTudo">
                    <div id="DivA">Data de Nascimento:</div>
                    <div id="DivB"><?php echo date('d/m/Y', $this->pessoa->dataNascimento) ?></div>
                </div>
                <hr>
                <div id="DivTudo">
                    <div id="DivA">Telefone:</div>
                    <div id="DivB"><?php echo (strlen($this->pessoa->telefone) <= 10) ? $this->mascara($this->pessoa->telefone, '(##) ####-####') : $this->mascara($this->pessoa->telefone, '(##) #####-####') ?></div>                           
                </div>
                <hr>
                <div id="DivTudo">
                    <div id="DivA">E-Mail:</div>
                    <div id="DivB"><?php echo $this->pessoa->email ?></div>
                </div>
                <hr>
                <div id="DivTudo">
                    <div id="DivA">Tipo de Pessoa:</div>
                    <div id="DivB"><?php echo $this->pessoa($this->pessoa->tipoPessoa); ?></div>

                </div>
                <hr>
                <div id="DivTudo">
                    <div id="DivA">Observação:</div>
                    <div id="DivB"><?php echo nl2br($this->pessoa->observacao) ?></div>
                </div>
            </div>
        </div>
        <div class="text-center">
            <p><a class="btn btn-primary tamanho-botao" style="color: white; text-decoration: none" href="/person">Voltar</a></p>
            <p><a class="btn btn-primary tamanho-botao" style="color: white; text-decoration: none" href="<?php echo $this->url(array('controller' => 'person', 'action' => 'edit')); ?>">Editar Pessoa</a></p>
        </div>
    </div>



