<div class="jumbotron">
    <div style="text-align: center;" class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <img class="img-circle" src="/imagens/season_logo_vermelho.png" alt="Logo Season" width="55" height="55"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <p class="titulo">Seja Bem Vindo!</p>
                <p class="sub">Acesse os itens "Usuários", "Pessoas" e "Treinamentos" para realizar o cadastro de novas informações.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4">
                <a href="/users" class="btn btn-primary">Usuários</a>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <a href="/person" class="btn btn-primary">Pessoas</a>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <a href="/training" class="btn btn-primary">Treinamentos</a>
            </div>
        </div>
    </div>
    &nbsp;
</div>