<!DOCTYPE html>
<html lang="br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Home">
        <meta name="author" content="Ana Beatriz Araujo">

        <title>Season Treinamentos</title>
        <link rel="shortcut icon" href="/imagens/favicon (1).ico"/>

        <!-- Bootstrap core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <!--        <link href="signin.css" rel="stylesheet">-->
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/view.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/pagInicial.css" />
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.maskedinput.js" /></script>
<!--        <script type="text/javascript" src="jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="jquery.mask.min.js"></script>-->

    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="/index">
                        <img class="img-circle" src="/imagens/season_logo_vermelho.png" alt="Logo Season" width="22" height="22"/>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="/users">Usuários<span class="sr-only">(current)</span></a></li>
                        <li><a href="/person">Pessoas</a></li>
                        <li><a href="/training">Treinamentos<span class="sr-only">(current)</span></a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <p class="navbar-text"><font color="white" >
                            Bem vindo,&nbsp;<?php echo Zend_Auth::getInstance()->getStorage()->read()->nome ?>! 
                            </font></p></li>
                        <li><a href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout')) ?>">Sair</a></li>
                    </ul>

                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container-fluid">
            <?php echo $this->layout()->content; ?>
        </div>

    </body>
</html>

