<head>
    <title>Adicionar Treinamento</title>
</head>

<body>
    <div class="container-fluid">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p class="h3 mb-3 font-weight-normal text-center" style="font-family: Calibri Light, sans-serif; font-weight: bold">Adicionar novo Treinamento</p>
                </div>
                <div class="panel-body">
                    <?php echo $this->form; ?>
                </div> 
            </div>
        </div>
    </div>
</body>


